  
# 核心任务

- name: activemq
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"}  
    - {role: role_jdk, tags: "role_jdk"}  
    - {role: active_mq, tags: "active_mq"}
    - {role: role_end, tags: "role_end"}