  
# # 服务器前置任务(ubuntu使用)
- name: Pre_tasks of ActiceMQ
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt-get -y install python


# # 核心任务

- name: ActiceMQ
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}  
    - { role: activemq, tags: "activemq"}
    - { role: end, tags: "end"}