---

# pre-installation

- set_fact:
    activemq_download_url: "{{activemq_meta[activemq_distribution].download_url}}"

- name: Add ActiveMQ User
  user:
    name: activemq
    shell: /usr/sbin/nologin
    home: /opt/apache-activemq
    create_home: no
    
- name: Remove extra dir for re-installation
  shell: rm -rf /opt/apache-activemq
  
- name: Download ActiveMQ
  unarchive:
    src: "{{activemq_download_url}}"
    dest: /opt/
    remote_src: yes
    owner: activemq
    group: activemq
    
- name: Rename the ActiveMQ after download
  shell: mv /opt/apache-activemq-* /opt/apache-activemq

# install by OS family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure
- name: Add x authority for activemq
  shell: chmod +x /opt/apache-activemq/bin/activemq

- name: Setting Environment variable for activemq
  shell: echo 'export PATH="$PATH:/opt/apache-activemq/bin"' >> /etc/profile

- name: Configuration ActiveMQ Server
  copy:
    src: activemq.service
    dest: /lib/systemd/system/

- name: Start ActiveMQ
  service:
    name: activemq
    state: started
    enabled: yes

- name: Setting File Permission
  shell: chmod 640  /opt/apache-activemq/examples/stomp/php/*

- name: Setting Owner and  Group
  shell: chown -R activemq. /opt/apache-activemq

# print version
- block:
  - name: Check ActiveMQ Version
    shell: ls /opt/apache-activemq | grep activemq
    register: check_activemq_version
    notify: check_activemq_version

  - name: Check ActiveMQ Service
    shell: systemctl status activemq | grep Active*
    register: check_activemq_service
    notify: check_activemq_service
