---
- name: Add ActiveMQ User
  user:
    name: activemq
    shell: /usr/sbin/nologin
    home: /opt/apache-activemq
    create_home: no

- name: Download ActiveMQ
  unarchive:
    src: "{{activemq_download_url}}"
    dest: /opt/
    remote_src: yes
    owner: activemq
    group: activemq
    
- shell: mv /opt/apache-activemq-* /opt/apache-activemq

- shell: chmod +x /opt/apache-activemq/bin/activemq

- name: Setting Environment
  shell: echo 'export PATH="$PATH:/opt/apache-activemq/bin"' >> /etc/profile

- name: Configuration ActiveMQ Server
  copy:
    src: activemq.service
    dest: /lib/systemd/system/

- name: Start ActiveMQ
  service:
    name: activemq
    state: started
    enabled: yes

- name: Setting File Permission
  shell: chmod 640  /opt/apache-activemq/examples/stomp/php/*

- name: Setting Owner and  Group
  shell: chown -R activemq. /opt/apache-activemq
